fix wrong namespaceSelector in servicemonitor
coredns/helm pull request #127
Opened 2023-07-05 07:08 UTC by tulequ

#### Why is this pull request needed and what does it do?
when set prometheus.monitor.namespace to differ namespace, we should use namespaceSelector to specify service namespace

#### Which issues (if any) are related?

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#versioning).
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Changes are automatically published when merged to `main`. They are not published on branches.

<details>
  <summary>Note on DCO</summary>

  If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

2023-07-05 16:14 UTC, hagaibarel commented
Not sure I understand the change, shouldn't the namespace selector always be the release namespace? In what cases should the service monitor be targeting a different namespace?

2023-07-06 10:29 UTC, tulequ commented
Because some prometheus is deployed with servicemonitor namespace to `monitoring` only (I don't think it is good, but it is historical)

I give some example
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/controller-servicemonitor.yaml (this is complex :)) )
https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/servicemonitor.yaml
https://github.com/bitnami/charts/blob/main/bitnami/rabbitmq/templates/servicemonitor.yaml

2023-07-06 18:21 UTC, hagaibarel commented
Alright, sounds reasonable, please fill out all the items in the PR task list and we can get this rolling (e.g. DCO)

2023-07-10 09:44 UTC, hagaibarel requested changes

2023-07-10 09:44 UTC, hagaibarel commented on charts/coredns/Chart.yaml
> +      description: Wrong namespaceSelector is ServiceMonitor when use custom monitoring namespace
Small nit, just to make the wording more clear

```suggestion
      description: Fix wrong namespaceSelector in ServiceMonitor when using custom monitoring namespace
```

2023-07-10 11:08 UTC, hagaibarel commented
@tulequ the DCO check is failing, please resolve

2023-08-05 08:45 UTC, hagaibarel commented
Seems like the DCO check is still failing, please fix so we can merge this

2023-08-08 02:41 UTC, tulequ commented
please check again

2023-08-08 03:37 UTC, hagaibarel approved these changes

2023-08-08 03:37 UTC, merged

2023-08-08 03:37 UTC, hagaibarel commented
Thanks!