feat(coredns,helmchart): template topologySpreadConstraints
coredns/helm pull request #145
Opened 2023-10-31 16:00 UTC by DrBu7cher

#### Why is this pull request needed and what does it do?

This PR implements a templating functionality for topologySpreadConstraints, similar to what the official ingress-nginx HelmChart offers.
Compare: https://github.com/kubernetes/ingress-nginx/blob/helm-chart-4.8.3/charts/ingress-nginx/templates/controller-
deployment.yaml#L212
This makes it easier to remove redundant information and can lead to less copy-paste related errors. Also, some people might call it more convenient.

#### Which issues (if any) are related?
None

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#versioning).
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Changes are automatically published when merged to `main`. They are not published on branches.

<details>
  <summary>Note on DCO</summary>

  If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

2023-10-31 16:07 UTC, DrBu7cher commented on charts/coredns/Chart.yaml
> -      description: Fixed indentation for sidecar containers
Should I have kept these changes?

2023-10-31 16:37 UTC, hagaibarel requested changes

2023-10-31 16:37 UTC, hagaibarel commented on charts/coredns/Chart.yaml
> +version: 1.27.2
```suggestion
version: 1.28.0
```

2023-10-31 16:56 UTC, hagaibarel commented
Please rebase from latest master, I updated some github actions in https://github.com/coredns/helm/pull/146 that caused the runs to fail

2023-11-02 08:09 UTC, hagaibarel approved these changes

2023-11-02 08:10 UTC, merged