Allow defaultMode override for extraSecrets
coredns/helm pull request #147
Opened 2023-11-01 14:30 UTC by JT-IT

#### Why is this pull request needed and what does it do?
This request is needed because the `defaultMode` value of `400` is hardcoded into the [deployment.yaml file](https://github.com/coredns/helm/blob/master/charts/coredns/templates/deployment.yaml#L156) for any secrets defined in  `.Values.extraSecrets` which causes the CoreDNS pod to crash loop when using etcd as a back end with a "permission denied" error for the file mounted.  Changing this to `420` resolves the issue, but the user should be able to set the `defaultMode` using the values file.  This exposes the setting but uses a default of `400`.
#### Which issues (if any) are related?
https://github.com/coredns/helm/issues/144

Checklist:

* [x] I have bumped the chart version according to [versioning](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#versioning).
* [x] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#changelog).
* [x] Any new values are backwards compatible and/or have sensible default.
* [x] I have signed off all my commits as required by [DCO](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Changes are automatically published when merged to `main`. They are not published on branches.

<details>
  <summary>Note on DCO</summary>

  If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

2023-11-01 15:27 UTC, slucheninov approved these changes

2023-11-02 08:08 UTC, hagaibarel requested changes

2023-11-02 08:08 UTC, hagaibarel commented on .github/workflows/lint-test.yaml
> +        uses: helm/chart-testing-action@v2.6.0
These were already changed in https://github.com/coredns/helm/pull/146, please remove the changes to the workflow files

2023-11-02 08:08 UTC, hagaibarel commented on charts/coredns/Chart.yaml
>        description: Fixed indentation for sidecar containers
Remove the previous entries, the changes section should contain only the changes related to this release

2023-11-02 13:09 UTC, closed without merging