Allow to skip ConfigMap creation
coredns/helm pull request #167
Opened 2024-05-19 18:53 UTC by cep21

#### Why is this pull request needed and what does it do?

A requested rebase and merge from PR #41

#### Which issues (if any) are related?

Checklist:

* [ ] I have bumped the chart version according to [versioning](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#versioning).
* [ ] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#changelog).
* [ ] Any new values are backwards compatible and/or have sensible default.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Changes are automatically published when merged to `main`. They are not published on branches.

<details>
  <summary>Note on DCO</summary>

  If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

2024-05-19 19:06 UTC, cep21 commented
Hi @hagaibarel , this is the rebased PR

2024-05-28 08:15 UTC, hagaibarel requested changes

2024-05-28 08:15 UTC, hagaibarel commented on charts/coredns/Chart.yaml
> +      description: Ability to skip configmap management
Please remove the other lines in the `changes` section, leave only these two

2024-05-29 07:15 UTC, hagaibarel commented
@cep21 I think the last commit wasn't properly signed-off, please fix

2024-05-29 20:26 UTC, cep21 commented
> @cep21 I think the last commit wasn't properly signed-off, please fix

Fixed!

2024-05-30 07:38 UTC, hagaibarel approved these changes

2024-05-30 07:38 UTC, merged

2024-05-30 07:38 UTC, hagaibarel commented
@cep21 great job, thanks for working on this