Allow overriding selectors and names
coredns/helm pull request #168
Opened 2024-05-22 17:44 UTC by alex-berger

#### Why is this pull request needed and what does it do?

This allows adapting to non-standard setups like for example AWS EKS CoreDNS Add-on, which use different labels, selectors and object names. Specifically it allows 

- overriding of selectors for _Deployment_, _Services_, _PodDisruptionBudget_ and _ServiceMonitor_.
- overriding the _ClusterRole_ and _ClusterRoleBinding_ names.

This is achieved by introducing the following optional new settings:

| Parameter                                      | Description                                                                                                                               | Default                                                      |
| :--------------------------------------------- | :---------------------------------------------------------------------------------------------------------------------------------------- | :----------------------------------------------------------- |
| `service.selector`                             | Pod selector                                                                                                                              | `{}`                                                         |
| `deployment.selector`                          | Pod selector                                                                                                                              | `{}`                                                         |
| `prometheus.service.selector`                  | Pod selector                                                                                                                              | `{}`                                                         |
| `prometheus.monitor.selector`                  | Service selector                                                                                                                          | `{}`                                                         |
| `clusterRole.nameOverride`                     | ClusterRole name override                                                                                                                 |                                                              |

The changes are fully backward compatible and one has to explicitly opt-in to override the default behavior. 

#### Which issues (if any) are related?

- https://github.com/coredns/helm/issues/97

Checklist:

* [X] I have bumped the chart version according to [versioning](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#versioning).
* [X] I have updated the chart changelog with all the changes that come with this pull request according to [changelog](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#changelog).
* [X] Any new values are backwards compatible and/or have sensible default.
* [X] I have signed off all my commits as required by [DCO](https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#developer-certificate-of-origin).

Changes are automatically published when merged to `main`. They are not published on branches.

<details>
  <summary>Note on DCO</summary>

  If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

2024-06-06 19:27 UTC, joshuabaird commented
This would be very helpful for users who are trying to install the helm chart over a "stock" EKS deployment or even a deployment where the managed EKS addon for coredns is being used.

2024-06-10 06:28 UTC, alex-berger commented
Randomly notifying one of the maintainers for review @mrueg, no urgency or pressure, just would love to make progress on this 😇.

2024-06-13 07:58 UTC, hagaibarel requested changes
Small nit, otherwise LGTM

2024-06-13 07:58 UTC, hagaibarel commented on charts/coredns/Chart.yaml
> +version: 1.30.1
Let's up the minor version, we're adding stuff not just fixing

```suggestion
version: 1.31.0
```

2024-06-13 13:00 UTC, merged

2024-06-13 13:00 UTC, hagaibarel commented
Thanks @alex-berger !

2024-06-13 13:26 UTC, joshuabaird commented
Thanks, @alex-berger!