Add support for ServiceAccount annotations
coredns/helm pull request #4
Opened 2021-01-27 10:15 UTC by alex-berger

This PR adds support for passing ServiceAccount annotations, which is required for example to deploy CoreDNS on AWS EKS with IAM Role ARN in annotations.

Furthermore, this PR also fixes #3.

2021-01-27 22:54 UTC, haad requested changes
Pls remove your changes to deployment.yaml. Otherwise LGTM.

2021-01-27 22:54 UTC, haad commented on stable/coredns/templates/deployment.yaml
> -        {{- if .Values.customLabels }}
Can you remove this change. It is not related to PR nor necessary.

2021-01-27 23:01 UTC, haad commented
LGTM

2021-01-27 23:03 UTC, haad commented
Can you pls bump patch chart version.

2021-01-28 08:37 UTC, merged

2021-01-28 08:50 UTC, rustrial commented
@haad Thank you very much for fast merging and releasing.