Fix pullSecrets, fix assignment of NET_BIND_SERVICE capability
coredns/helm pull request #93
Opened 2023-02-06 11:58 UTC by firefrei

I tried to use the helm chart in v1.19.7 on our RKE2-based Kubernetes cluster which has special hardening according to CIS-1.6 implemented. However, the images could not be pulled from our private repo as well as the pods terminated with "operation not permitted".

The reason for these two errors were:
- imagePullSecrets were not used (mentioned in values.yaml as image.pullSecrets, but not evaluated in template)
- the NET_BIND_SERVICE capability was not set in securityContext of pod
  - securityContext was not mentioned in values.yaml, however it was evaluated in template.
- in the PSP element, the capability was named incorrectly. It was CAP_NET_BIND_SERVICE, however, due to official K8s docs, there should be no `CAP_` prefix.

This MR fixes all these issues. It tested the helm chart with these fixes, the pods are now able to start!

2023-02-06 13:07 UTC, firefrei commented
Hmmm... the linter complains that I did not bump the version number. Should I do this?

```
 ✖︎ coredns => (version: "1.19.7", path: "charts/coredns") > chart version not ok. Needs a version bump! 
```

2023-02-07 10:36 UTC, firefrei commented
@mrueg Okay, so when I have `serviceAccount.create` set to false, which is the default, then I cannot use an imagePullSecret? What's the idea behind this? 

https://github.com/coredns/helm/blob/2fd88c262f883adee5978f8b8923f72a04e2264b/charts/coredns/templates/serviceaccount.yaml#L1

2023-02-13 08:13 UTC, firefrei commented
@mrueg how should we proceed with this PR?
What is the desired way of using imagePullSecrets? I would suggest to use it with the Deployment, to not rely on the service account.
Should I extend the PR and remove it from the ServiceAccount? Should I remove the imagePullSecret again from the Deployment and limit this PR to the NET_BIND_SERVIC fix?

2023-03-23 08:56 UTC, HagaiBarel commented
Hi @firefrei I agree with you that specifying a `pullSecret` is much more common on the deployment than on the service account, because the service account is conditional. I think we can proceed with the PR as-is. Please rebase and bump the chart version by a minor version

2023-04-04 09:02 UTC, hagaibarel commented
Thanks, looking good, one last thing is to update the changelog, see https://github.com/coredns/helm/blob/master/CONTRIBUTING.md#changelog for instructions on what and how

2023-04-04 18:15 UTC, firefrei commented
Done! I hope I inserted the item at the correct position in in the list :-)

2023-04-09 05:34 UTC, hagaibarel requested changes

2023-04-09 05:34 UTC, hagaibarel commented on charts/coredns/Chart.yaml
> +      description: Fix assignment of NET_BIND_SERVICE capability, enable use of pullSecrets with Deployment
This should completely replace the current change log, not append to it. Also, please break it down to 2 items. The final structure should look similar to:

```yaml
artifacthub.io/changes: |
  - kind: fixed
    description: Fix assignment of NET_BIND_SERVICE capability
  - kind: fixed
    description: Enable use of pullSecrets with Deployment
```

2023-04-09 05:34 UTC, hagaibarel commented on charts/coredns/Chart.yaml
> +version: 1.21.0
We'll need another version increase based on the most recent chart version

2023-04-12 19:49 UTC, firefrei commented
Sorry for the delay,
next try :-)

2023-04-13 06:29 UTC, hagaibarel approved these changes

2023-04-13 06:30 UTC, merged